// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/KimNattanan/go-chat-backend/internal/message/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageRepo creates a new instance of MockMessageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepo {
	mock := &MockMessageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageRepo is an autogenerated mock type for the MessageRepo type
type MockMessageRepo struct {
	mock.Mock
}

type MockMessageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepo) EXPECT() *MockMessageRepo_Expecter {
	return &MockMessageRepo_Expecter{mock: &_m.Mock}
}

// AnonymizeUserMessages provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) AnonymizeUserMessages(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AnonymizeUserMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageRepo_AnonymizeUserMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnonymizeUserMessages'
type MockMessageRepo_AnonymizeUserMessages_Call struct {
	*mock.Call
}

// AnonymizeUserMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMessageRepo_Expecter) AnonymizeUserMessages(ctx interface{}, userID interface{}) *MockMessageRepo_AnonymizeUserMessages_Call {
	return &MockMessageRepo_AnonymizeUserMessages_Call{Call: _e.mock.On("AnonymizeUserMessages", ctx, userID)}
}

func (_c *MockMessageRepo_AnonymizeUserMessages_Call) Run(run func(ctx context.Context, userID string)) *MockMessageRepo_AnonymizeUserMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_AnonymizeUserMessages_Call) Return(err error) *MockMessageRepo_AnonymizeUserMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageRepo_AnonymizeUserMessages_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockMessageRepo_AnonymizeUserMessages_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) Create(ctx context.Context, message *entity.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - message *entity.Message
func (_e *MockMessageRepo_Expecter) Create(ctx interface{}, message interface{}) *MockMessageRepo_Create_Call {
	return &MockMessageRepo_Create_Call{Call: _e.mock.On("Create", ctx, message)}
}

func (_c *MockMessageRepo_Create_Call) Run(run func(ctx context.Context, message *entity.Message)) *MockMessageRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Message
		if args[1] != nil {
			arg1 = args[1].(*entity.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_Create_Call) Return(err error) *MockMessageRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageRepo_Create_Call) RunAndReturn(run func(ctx context.Context, message *entity.Message) error) *MockMessageRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMessageRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMessageRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockMessageRepo_Delete_Call {
	return &MockMessageRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMessageRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockMessageRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_Delete_Call) Return(err error) *MockMessageRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockMessageRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByRoomID provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) DeleteByRoomID(ctx context.Context, roomID string) error {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRoomID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageRepo_DeleteByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRoomID'
type MockMessageRepo_DeleteByRoomID_Call struct {
	*mock.Call
}

// DeleteByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockMessageRepo_Expecter) DeleteByRoomID(ctx interface{}, roomID interface{}) *MockMessageRepo_DeleteByRoomID_Call {
	return &MockMessageRepo_DeleteByRoomID_Call{Call: _e.mock.On("DeleteByRoomID", ctx, roomID)}
}

func (_c *MockMessageRepo_DeleteByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockMessageRepo_DeleteByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_DeleteByRoomID_Call) Return(err error) *MockMessageRepo_DeleteByRoomID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageRepo_DeleteByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) error) *MockMessageRepo_DeleteByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) FindByID(ctx context.Context, id string) (*entity.Message, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Message, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Message); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMessageRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMessageRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockMessageRepo_FindByID_Call {
	return &MockMessageRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMessageRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockMessageRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_FindByID_Call) Return(message *entity.Message, err error) *MockMessageRepo_FindByID_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessageRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Message, error)) *MockMessageRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoomID provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) FindByRoomID(ctx context.Context, roomID string) ([]*entity.Message, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoomID")
	}

	var r0 []*entity.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Message, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Message); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepo_FindByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoomID'
type MockMessageRepo_FindByRoomID_Call struct {
	*mock.Call
}

// FindByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockMessageRepo_Expecter) FindByRoomID(ctx interface{}, roomID interface{}) *MockMessageRepo_FindByRoomID_Call {
	return &MockMessageRepo_FindByRoomID_Call{Call: _e.mock.On("FindByRoomID", ctx, roomID)}
}

func (_c *MockMessageRepo_FindByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockMessageRepo_FindByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_FindByRoomID_Call) Return(messages []*entity.Message, err error) *MockMessageRepo_FindByRoomID_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageRepo_FindByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) ([]*entity.Message, error)) *MockMessageRepo_FindByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoomIDAndUserID provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) FindByRoomIDAndUserID(ctx context.Context, roomID string, userID string) ([]*entity.Message, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoomIDAndUserID")
	}

	var r0 []*entity.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*entity.Message, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*entity.Message); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepo_FindByRoomIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoomIDAndUserID'
type MockMessageRepo_FindByRoomIDAndUserID_Call struct {
	*mock.Call
}

// FindByRoomIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockMessageRepo_Expecter) FindByRoomIDAndUserID(ctx interface{}, roomID interface{}, userID interface{}) *MockMessageRepo_FindByRoomIDAndUserID_Call {
	return &MockMessageRepo_FindByRoomIDAndUserID_Call{Call: _e.mock.On("FindByRoomIDAndUserID", ctx, roomID, userID)}
}

func (_c *MockMessageRepo_FindByRoomIDAndUserID_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockMessageRepo_FindByRoomIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessageRepo_FindByRoomIDAndUserID_Call) Return(messages []*entity.Message, err error) *MockMessageRepo_FindByRoomIDAndUserID_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageRepo_FindByRoomIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, roomID string, userID string) ([]*entity.Message, error)) *MockMessageRepo_FindByRoomIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockMessageRepo
func (_mock *MockMessageRepo) FindByUserID(ctx context.Context, userID string) ([]*entity.Message, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Message, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Message); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockMessageRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMessageRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockMessageRepo_FindByUserID_Call {
	return &MockMessageRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockMessageRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockMessageRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageRepo_FindByUserID_Call) Return(messages []*entity.Message, err error) *MockMessageRepo_FindByUserID_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageRepo_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Message, error)) *MockMessageRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}
