// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/KimNattanan/go-chat-backend/internal/auth/proto/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockAuthServiceClient creates a new instance of MockAuthServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthServiceClient is an autogenerated mock type for the AuthServiceClient type
type MockAuthServiceClient struct {
	mock.Mock
}

type MockAuthServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceClient) EXPECT() *MockAuthServiceClient_Expecter {
	return &MockAuthServiceClient_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) DeleteUser(ctx context.Context, in *v1.DeleteUserRequest, opts ...grpc.CallOption) (*v1.DeleteUserResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *v1.DeleteUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteUserRequest, ...grpc.CallOption) (*v1.DeleteUserResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.DeleteUserRequest, ...grpc.CallOption) *v1.DeleteUserResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.DeleteUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.DeleteUserRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockAuthServiceClient_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.DeleteUserRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) DeleteUser(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_DeleteUser_Call {
	return &MockAuthServiceClient_DeleteUser_Call{Call: _e.mock.On("DeleteUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_DeleteUser_Call) Run(run func(ctx context.Context, in *v1.DeleteUserRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.DeleteUserRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.DeleteUserRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_DeleteUser_Call) Return(deleteUserResponse *v1.DeleteUserResponse, err error) *MockAuthServiceClient_DeleteUser_Call {
	_c.Call.Return(deleteUserResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, in *v1.DeleteUserRequest, opts ...grpc.CallOption) (*v1.DeleteUserResponse, error)) *MockAuthServiceClient_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) FindUserByEmail(ctx context.Context, in *v1.FindUserByEmailRequest, opts ...grpc.CallOption) (*v1.UserResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *v1.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.FindUserByEmailRequest, ...grpc.CallOption) (*v1.UserResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.FindUserByEmailRequest, ...grpc.CallOption) *v1.UserResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.FindUserByEmailRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockAuthServiceClient_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.FindUserByEmailRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) FindUserByEmail(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_FindUserByEmail_Call {
	return &MockAuthServiceClient_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_FindUserByEmail_Call) Run(run func(ctx context.Context, in *v1.FindUserByEmailRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.FindUserByEmailRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.FindUserByEmailRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_FindUserByEmail_Call) Return(userResponse *v1.UserResponse, err error) *MockAuthServiceClient_FindUserByEmail_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, in *v1.FindUserByEmailRequest, opts ...grpc.CallOption) (*v1.UserResponse, error)) *MockAuthServiceClient_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) FindUserByID(ctx context.Context, in *v1.FindUserByIDRequest, opts ...grpc.CallOption) (*v1.UserResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *v1.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.FindUserByIDRequest, ...grpc.CallOption) (*v1.UserResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.FindUserByIDRequest, ...grpc.CallOption) *v1.UserResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.FindUserByIDRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockAuthServiceClient_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.FindUserByIDRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) FindUserByID(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_FindUserByID_Call {
	return &MockAuthServiceClient_FindUserByID_Call{Call: _e.mock.On("FindUserByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_FindUserByID_Call) Run(run func(ctx context.Context, in *v1.FindUserByIDRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.FindUserByIDRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.FindUserByIDRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_FindUserByID_Call) Return(userResponse *v1.UserResponse, err error) *MockAuthServiceClient_FindUserByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_FindUserByID_Call) RunAndReturn(run func(ctx context.Context, in *v1.FindUserByIDRequest, opts ...grpc.CallOption) (*v1.UserResponse, error)) *MockAuthServiceClient_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) Login(ctx context.Context, in *v1.LoginRequest, opts ...grpc.CallOption) (*v1.LoginResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *v1.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.LoginRequest, ...grpc.CallOption) (*v1.LoginResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.LoginRequest, ...grpc.CallOption) *v1.LoginResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServiceClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_Login_Call {
	return &MockAuthServiceClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_Login_Call) Run(run func(ctx context.Context, in *v1.LoginRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.LoginRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.LoginRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_Login_Call) Return(loginResponse *v1.LoginResponse, err error) *MockAuthServiceClient_Login_Call {
	_c.Call.Return(loginResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_Login_Call) RunAndReturn(run func(ctx context.Context, in *v1.LoginRequest, opts ...grpc.CallOption) (*v1.LoginResponse, error)) *MockAuthServiceClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) Logout(ctx context.Context, in *v1.LogoutRequest, opts ...grpc.CallOption) (*v1.LogoutResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *v1.LogoutResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.LogoutRequest, ...grpc.CallOption) (*v1.LogoutResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.LogoutRequest, ...grpc.CallOption) *v1.LogoutResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.LogoutResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.LogoutRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServiceClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.LogoutRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) Logout(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_Logout_Call {
	return &MockAuthServiceClient_Logout_Call{Call: _e.mock.On("Logout",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_Logout_Call) Run(run func(ctx context.Context, in *v1.LogoutRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.LogoutRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.LogoutRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_Logout_Call) Return(logoutResponse *v1.LogoutResponse, err error) *MockAuthServiceClient_Logout_Call {
	_c.Call.Return(logoutResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_Logout_Call) RunAndReturn(run func(ctx context.Context, in *v1.LogoutRequest, opts ...grpc.CallOption) (*v1.LogoutResponse, error)) *MockAuthServiceClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) RefreshToken(ctx context.Context, in *v1.RefreshTokenRequest, opts ...grpc.CallOption) (*v1.RefreshTokenResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *v1.RefreshTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.RefreshTokenRequest, ...grpc.CallOption) (*v1.RefreshTokenResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.RefreshTokenRequest, ...grpc.CallOption) *v1.RefreshTokenResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RefreshTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.RefreshTokenRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthServiceClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.RefreshTokenRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) RefreshToken(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_RefreshToken_Call {
	return &MockAuthServiceClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_RefreshToken_Call) Run(run func(ctx context.Context, in *v1.RefreshTokenRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.RefreshTokenRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.RefreshTokenRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_RefreshToken_Call) Return(refreshTokenResponse *v1.RefreshTokenResponse, err error) *MockAuthServiceClient_RefreshToken_Call {
	_c.Call.Return(refreshTokenResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, in *v1.RefreshTokenRequest, opts ...grpc.CallOption) (*v1.RefreshTokenResponse, error)) *MockAuthServiceClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthServiceClient
func (_mock *MockAuthServiceClient) Register(ctx context.Context, in *v1.RegisterRequest, opts ...grpc.CallOption) (*v1.RegisterResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *v1.RegisterResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.RegisterRequest, ...grpc.CallOption) (*v1.RegisterResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.RegisterRequest, ...grpc.CallOption) *v1.RegisterResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RegisterResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServiceClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServiceClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.RegisterRequest
//   - opts ...grpc.CallOption
func (_e *MockAuthServiceClient_Expecter) Register(ctx interface{}, in interface{}, opts ...interface{}) *MockAuthServiceClient_Register_Call {
	return &MockAuthServiceClient_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockAuthServiceClient_Register_Call) Run(run func(ctx context.Context, in *v1.RegisterRequest, opts ...grpc.CallOption)) *MockAuthServiceClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.RegisterRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuthServiceClient_Register_Call) Return(registerResponse *v1.RegisterResponse, err error) *MockAuthServiceClient_Register_Call {
	_c.Call.Return(registerResponse, err)
	return _c
}

func (_c *MockAuthServiceClient_Register_Call) RunAndReturn(run func(ctx context.Context, in *v1.RegisterRequest, opts ...grpc.CallOption) (*v1.RegisterResponse, error)) *MockAuthServiceClient_Register_Call {
	_c.Call.Return(run)
	return _c
}
