// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/KimNattanan/go-chat-backend/internal/profile/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfileRepo creates a new instance of MockProfileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepo {
	mock := &MockProfileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileRepo is an autogenerated mock type for the ProfileRepo type
type MockProfileRepo struct {
	mock.Mock
}

type MockProfileRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepo) EXPECT() *MockProfileRepo_Expecter {
	return &MockProfileRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProfileRepo
func (_mock *MockProfileRepo) Create(ctx context.Context, profile *entity.Profile) error {
	ret := _mock.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Profile) error); ok {
		r0 = returnFunc(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProfileRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *entity.Profile
func (_e *MockProfileRepo_Expecter) Create(ctx interface{}, profile interface{}) *MockProfileRepo_Create_Call {
	return &MockProfileRepo_Create_Call{Call: _e.mock.On("Create", ctx, profile)}
}

func (_c *MockProfileRepo_Create_Call) Run(run func(ctx context.Context, profile *entity.Profile)) *MockProfileRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Profile
		if args[1] != nil {
			arg1 = args[1].(*entity.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepo_Create_Call) Return(err error) *MockProfileRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepo_Create_Call) RunAndReturn(run func(ctx context.Context, profile *entity.Profile) error) *MockProfileRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProfileRepo
func (_mock *MockProfileRepo) Delete(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProfileRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockProfileRepo_Expecter) Delete(ctx interface{}, userID interface{}) *MockProfileRepo_Delete_Call {
	return &MockProfileRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockProfileRepo_Delete_Call) Run(run func(ctx context.Context, userID string)) *MockProfileRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepo_Delete_Call) Return(err error) *MockProfileRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockProfileRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockProfileRepo
func (_mock *MockProfileRepo) FindByUserID(ctx context.Context, userID string) (*entity.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *entity.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockProfileRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockProfileRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockProfileRepo_FindByUserID_Call {
	return &MockProfileRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockProfileRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockProfileRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepo_FindByUserID_Call) Return(profile *entity.Profile, err error) *MockProfileRepo_FindByUserID_Call {
	_c.Call.Return(profile, err)
	return _c
}

func (_c *MockProfileRepo_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*entity.Profile, error)) *MockProfileRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockProfileRepo
func (_mock *MockProfileRepo) Patch(ctx context.Context, userID string, profile *entity.Profile) error {
	ret := _mock.Called(ctx, userID, profile)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *entity.Profile) error); ok {
		r0 = returnFunc(ctx, userID, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfileRepo_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockProfileRepo_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - profile *entity.Profile
func (_e *MockProfileRepo_Expecter) Patch(ctx interface{}, userID interface{}, profile interface{}) *MockProfileRepo_Patch_Call {
	return &MockProfileRepo_Patch_Call{Call: _e.mock.On("Patch", ctx, userID, profile)}
}

func (_c *MockProfileRepo_Patch_Call) Run(run func(ctx context.Context, userID string, profile *entity.Profile)) *MockProfileRepo_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *entity.Profile
		if args[2] != nil {
			arg2 = args[2].(*entity.Profile)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileRepo_Patch_Call) Return(err error) *MockProfileRepo_Patch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfileRepo_Patch_Call) RunAndReturn(run func(ctx context.Context, userID string, profile *entity.Profile) error) *MockProfileRepo_Patch_Call {
	_c.Call.Return(run)
	return _c
}
