// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/message/proto/v1/message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageService_FindMessageByID_FullMethodName               = "/message.v1.MessageService/FindMessageByID"
	MessageService_FindMessagesByRoomID_FullMethodName          = "/message.v1.MessageService/FindMessagesByRoomID"
	MessageService_FindMessagesByUserID_FullMethodName          = "/message.v1.MessageService/FindMessagesByUserID"
	MessageService_FindMessagesByRoomIDAndUserID_FullMethodName = "/message.v1.MessageService/FindMessagesByRoomIDAndUserID"
	MessageService_CreateMessage_FullMethodName                 = "/message.v1.MessageService/CreateMessage"
	MessageService_AnonymizeUserMessages_FullMethodName         = "/message.v1.MessageService/AnonymizeUserMessages"
	MessageService_DeleteMessage_FullMethodName                 = "/message.v1.MessageService/DeleteMessage"
	MessageService_DeleteMessagesByRoomID_FullMethodName        = "/message.v1.MessageService/DeleteMessagesByRoomID"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	FindMessageByID(ctx context.Context, in *FindMessageByIDRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	FindMessagesByRoomID(ctx context.Context, in *FindMessagesByRoomIDRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	FindMessagesByUserID(ctx context.Context, in *FindMessagesByUserIDRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	FindMessagesByRoomIDAndUserID(ctx context.Context, in *FindMessagesByRoomIDAndUserIDRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	AnonymizeUserMessages(ctx context.Context, in *AnonymizeUserMessagesRequest, opts ...grpc.CallOption) (*AnonymizeUserMessagesResponse, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
	DeleteMessagesByRoomID(ctx context.Context, in *DeleteMessagesByRoomIDRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) FindMessageByID(ctx context.Context, in *FindMessageByIDRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, MessageService_FindMessageByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) FindMessagesByRoomID(ctx context.Context, in *FindMessagesByRoomIDRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_FindMessagesByRoomID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) FindMessagesByUserID(ctx context.Context, in *FindMessagesByUserIDRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_FindMessagesByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) FindMessagesByRoomIDAndUserID(ctx context.Context, in *FindMessagesByRoomIDAndUserIDRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_FindMessagesByRoomIDAndUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, MessageService_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) AnonymizeUserMessages(ctx context.Context, in *AnonymizeUserMessagesRequest, opts ...grpc.CallOption) (*AnonymizeUserMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnonymizeUserMessagesResponse)
	err := c.cc.Invoke(ctx, MessageService_AnonymizeUserMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) DeleteMessagesByRoomID(ctx context.Context, in *DeleteMessagesByRoomIDRequest, opts ...grpc.CallOption) (*DeleteMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_DeleteMessagesByRoomID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
type MessageServiceServer interface {
	FindMessageByID(context.Context, *FindMessageByIDRequest) (*MessageResponse, error)
	FindMessagesByRoomID(context.Context, *FindMessagesByRoomIDRequest) (*MessagesResponse, error)
	FindMessagesByUserID(context.Context, *FindMessagesByUserIDRequest) (*MessagesResponse, error)
	FindMessagesByRoomIDAndUserID(context.Context, *FindMessagesByRoomIDAndUserIDRequest) (*MessagesResponse, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*MessageResponse, error)
	AnonymizeUserMessages(context.Context, *AnonymizeUserMessagesRequest) (*AnonymizeUserMessagesResponse, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error)
	DeleteMessagesByRoomID(context.Context, *DeleteMessagesByRoomIDRequest) (*DeleteMessageResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) FindMessageByID(context.Context, *FindMessageByIDRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMessageByID not implemented")
}
func (UnimplementedMessageServiceServer) FindMessagesByRoomID(context.Context, *FindMessagesByRoomIDRequest) (*MessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMessagesByRoomID not implemented")
}
func (UnimplementedMessageServiceServer) FindMessagesByUserID(context.Context, *FindMessagesByUserIDRequest) (*MessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMessagesByUserID not implemented")
}
func (UnimplementedMessageServiceServer) FindMessagesByRoomIDAndUserID(context.Context, *FindMessagesByRoomIDAndUserIDRequest) (*MessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMessagesByRoomIDAndUserID not implemented")
}
func (UnimplementedMessageServiceServer) CreateMessage(context.Context, *CreateMessageRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedMessageServiceServer) AnonymizeUserMessages(context.Context, *AnonymizeUserMessagesRequest) (*AnonymizeUserMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnonymizeUserMessages not implemented")
}
func (UnimplementedMessageServiceServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*DeleteMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMessageServiceServer) DeleteMessagesByRoomID(context.Context, *DeleteMessagesByRoomIDRequest) (*DeleteMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessagesByRoomID not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call panics, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_FindMessageByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMessageByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindMessageByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_FindMessageByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindMessageByID(ctx, req.(*FindMessageByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_FindMessagesByRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMessagesByRoomIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindMessagesByRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_FindMessagesByRoomID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindMessagesByRoomID(ctx, req.(*FindMessagesByRoomIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_FindMessagesByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMessagesByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindMessagesByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_FindMessagesByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindMessagesByUserID(ctx, req.(*FindMessagesByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_FindMessagesByRoomIDAndUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMessagesByRoomIDAndUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FindMessagesByRoomIDAndUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_FindMessagesByRoomIDAndUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FindMessagesByRoomIDAndUserID(ctx, req.(*FindMessagesByRoomIDAndUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_AnonymizeUserMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnonymizeUserMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).AnonymizeUserMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_AnonymizeUserMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).AnonymizeUserMessages(ctx, req.(*AnonymizeUserMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeleteMessagesByRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessagesByRoomIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).DeleteMessagesByRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_DeleteMessagesByRoomID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).DeleteMessagesByRoomID(ctx, req.(*DeleteMessagesByRoomIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.v1.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMessageByID",
			Handler:    _MessageService_FindMessageByID_Handler,
		},
		{
			MethodName: "FindMessagesByRoomID",
			Handler:    _MessageService_FindMessagesByRoomID_Handler,
		},
		{
			MethodName: "FindMessagesByUserID",
			Handler:    _MessageService_FindMessagesByUserID_Handler,
		},
		{
			MethodName: "FindMessagesByRoomIDAndUserID",
			Handler:    _MessageService_FindMessagesByRoomIDAndUserID_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _MessageService_CreateMessage_Handler,
		},
		{
			MethodName: "AnonymizeUserMessages",
			Handler:    _MessageService_AnonymizeUserMessages_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _MessageService_DeleteMessage_Handler,
		},
		{
			MethodName: "DeleteMessagesByRoomID",
			Handler:    _MessageService_DeleteMessagesByRoomID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/message/proto/v1/message.proto",
}
