// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/message/proto/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FindMessageByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMessageByIDRequest) Reset() {
	*x = FindMessageByIDRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMessageByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMessageByIDRequest) ProtoMessage() {}

func (x *FindMessageByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMessageByIDRequest.ProtoReflect.Descriptor instead.
func (*FindMessageByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *FindMessageByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindMessagesByRoomIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMessagesByRoomIDRequest) Reset() {
	*x = FindMessagesByRoomIDRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMessagesByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMessagesByRoomIDRequest) ProtoMessage() {}

func (x *FindMessagesByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMessagesByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*FindMessagesByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *FindMessagesByRoomIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type FindMessagesByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMessagesByUserIDRequest) Reset() {
	*x = FindMessagesByUserIDRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMessagesByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMessagesByUserIDRequest) ProtoMessage() {}

func (x *FindMessagesByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMessagesByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindMessagesByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *FindMessagesByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindMessagesByRoomIDAndUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMessagesByRoomIDAndUserIDRequest) Reset() {
	*x = FindMessagesByRoomIDAndUserIDRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMessagesByRoomIDAndUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMessagesByRoomIDAndUserIDRequest) ProtoMessage() {}

func (x *FindMessagesByRoomIDAndUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMessagesByRoomIDAndUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindMessagesByRoomIDAndUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *FindMessagesByRoomIDAndUserIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *FindMessagesByRoomIDAndUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnonymizeUserMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizeUserMessagesRequest) Reset() {
	*x = AnonymizeUserMessagesRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizeUserMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizeUserMessagesRequest) ProtoMessage() {}

func (x *AnonymizeUserMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizeUserMessagesRequest.ProtoReflect.Descriptor instead.
func (*AnonymizeUserMessagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *AnonymizeUserMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMessagesByRoomIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessagesByRoomIDRequest) Reset() {
	*x = DeleteMessagesByRoomIDRequest{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessagesByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessagesByRoomIDRequest) ProtoMessage() {}

func (x *DeleteMessagesByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessagesByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessagesByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMessagesByRoomIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type AnonymizeUserMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnonymizeUserMessagesResponse) Reset() {
	*x = AnonymizeUserMessagesResponse{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnonymizeUserMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnonymizeUserMessagesResponse) ProtoMessage() {}

func (x *AnonymizeUserMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnonymizeUserMessagesResponse.ProtoReflect.Descriptor instead.
func (*AnonymizeUserMessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *AnonymizeUserMessagesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *MessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesResponse) Reset() {
	*x = MessagesResponse{}
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesResponse) ProtoMessage() {}

func (x *MessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_message_proto_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesResponse.ProtoReflect.Descriptor instead.
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_message_proto_v1_message_proto_rawDescGZIP(), []int{12}
}

func (x *MessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_internal_message_proto_v1_message_proto protoreflect.FileDescriptor

const file_internal_message_proto_v1_message_proto_rawDesc = "" +
	"\n" +
	"'internal/message/proto/v1/message.proto\x12\n" +
	"message.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"(\n" +
	"\x16FindMessageByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x1bFindMessagesByRoomIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"6\n" +
	"\x1bFindMessagesByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"X\n" +
	"$FindMessagesByRoomIDAndUserIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"b\n" +
	"\x14CreateMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"7\n" +
	"\x1cAnonymizeUserMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"&\n" +
	"\x14DeleteMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x1dDeleteMessagesByRoomIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"9\n" +
	"\x1dAnonymizeUserMessagesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x15DeleteMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\x0fMessageResponse\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x13.message.v1.MessageR\amessage\"C\n" +
	"\x10MessagesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.message.v1.MessageR\bmessages2\x8f\x06\n" +
	"\x0eMessageService\x12R\n" +
	"\x0fFindMessageByID\x12\".message.v1.FindMessageByIDRequest\x1a\x1b.message.v1.MessageResponse\x12]\n" +
	"\x14FindMessagesByRoomID\x12'.message.v1.FindMessagesByRoomIDRequest\x1a\x1c.message.v1.MessagesResponse\x12]\n" +
	"\x14FindMessagesByUserID\x12'.message.v1.FindMessagesByUserIDRequest\x1a\x1c.message.v1.MessagesResponse\x12o\n" +
	"\x1dFindMessagesByRoomIDAndUserID\x120.message.v1.FindMessagesByRoomIDAndUserIDRequest\x1a\x1c.message.v1.MessagesResponse\x12N\n" +
	"\rCreateMessage\x12 .message.v1.CreateMessageRequest\x1a\x1b.message.v1.MessageResponse\x12l\n" +
	"\x15AnonymizeUserMessages\x12(.message.v1.AnonymizeUserMessagesRequest\x1a).message.v1.AnonymizeUserMessagesResponse\x12T\n" +
	"\rDeleteMessage\x12 .message.v1.DeleteMessageRequest\x1a!.message.v1.DeleteMessageResponse\x12f\n" +
	"\x16DeleteMessagesByRoomID\x12).message.v1.DeleteMessagesByRoomIDRequest\x1a!.message.v1.DeleteMessageResponseB\x1bZ\x19internal/message/proto/v1b\x06proto3"

var (
	file_internal_message_proto_v1_message_proto_rawDescOnce sync.Once
	file_internal_message_proto_v1_message_proto_rawDescData []byte
)

func file_internal_message_proto_v1_message_proto_rawDescGZIP() []byte {
	file_internal_message_proto_v1_message_proto_rawDescOnce.Do(func() {
		file_internal_message_proto_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_message_proto_v1_message_proto_rawDesc), len(file_internal_message_proto_v1_message_proto_rawDesc)))
	})
	return file_internal_message_proto_v1_message_proto_rawDescData
}

var file_internal_message_proto_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_message_proto_v1_message_proto_goTypes = []any{
	(*Message)(nil),                              // 0: message.v1.Message
	(*FindMessageByIDRequest)(nil),               // 1: message.v1.FindMessageByIDRequest
	(*FindMessagesByRoomIDRequest)(nil),          // 2: message.v1.FindMessagesByRoomIDRequest
	(*FindMessagesByUserIDRequest)(nil),          // 3: message.v1.FindMessagesByUserIDRequest
	(*FindMessagesByRoomIDAndUserIDRequest)(nil), // 4: message.v1.FindMessagesByRoomIDAndUserIDRequest
	(*CreateMessageRequest)(nil),                 // 5: message.v1.CreateMessageRequest
	(*AnonymizeUserMessagesRequest)(nil),         // 6: message.v1.AnonymizeUserMessagesRequest
	(*DeleteMessageRequest)(nil),                 // 7: message.v1.DeleteMessageRequest
	(*DeleteMessagesByRoomIDRequest)(nil),        // 8: message.v1.DeleteMessagesByRoomIDRequest
	(*AnonymizeUserMessagesResponse)(nil),        // 9: message.v1.AnonymizeUserMessagesResponse
	(*DeleteMessageResponse)(nil),                // 10: message.v1.DeleteMessageResponse
	(*MessageResponse)(nil),                      // 11: message.v1.MessageResponse
	(*MessagesResponse)(nil),                     // 12: message.v1.MessagesResponse
	(*timestamppb.Timestamp)(nil),                // 13: google.protobuf.Timestamp
}
var file_internal_message_proto_v1_message_proto_depIdxs = []int32{
	13, // 0: message.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: message.v1.MessageResponse.message:type_name -> message.v1.Message
	0,  // 2: message.v1.MessagesResponse.messages:type_name -> message.v1.Message
	1,  // 3: message.v1.MessageService.FindMessageByID:input_type -> message.v1.FindMessageByIDRequest
	2,  // 4: message.v1.MessageService.FindMessagesByRoomID:input_type -> message.v1.FindMessagesByRoomIDRequest
	3,  // 5: message.v1.MessageService.FindMessagesByUserID:input_type -> message.v1.FindMessagesByUserIDRequest
	4,  // 6: message.v1.MessageService.FindMessagesByRoomIDAndUserID:input_type -> message.v1.FindMessagesByRoomIDAndUserIDRequest
	5,  // 7: message.v1.MessageService.CreateMessage:input_type -> message.v1.CreateMessageRequest
	6,  // 8: message.v1.MessageService.AnonymizeUserMessages:input_type -> message.v1.AnonymizeUserMessagesRequest
	7,  // 9: message.v1.MessageService.DeleteMessage:input_type -> message.v1.DeleteMessageRequest
	8,  // 10: message.v1.MessageService.DeleteMessagesByRoomID:input_type -> message.v1.DeleteMessagesByRoomIDRequest
	11, // 11: message.v1.MessageService.FindMessageByID:output_type -> message.v1.MessageResponse
	12, // 12: message.v1.MessageService.FindMessagesByRoomID:output_type -> message.v1.MessagesResponse
	12, // 13: message.v1.MessageService.FindMessagesByUserID:output_type -> message.v1.MessagesResponse
	12, // 14: message.v1.MessageService.FindMessagesByRoomIDAndUserID:output_type -> message.v1.MessagesResponse
	11, // 15: message.v1.MessageService.CreateMessage:output_type -> message.v1.MessageResponse
	9,  // 16: message.v1.MessageService.AnonymizeUserMessages:output_type -> message.v1.AnonymizeUserMessagesResponse
	10, // 17: message.v1.MessageService.DeleteMessage:output_type -> message.v1.DeleteMessageResponse
	10, // 18: message.v1.MessageService.DeleteMessagesByRoomID:output_type -> message.v1.DeleteMessageResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_message_proto_v1_message_proto_init() }
func file_internal_message_proto_v1_message_proto_init() {
	if File_internal_message_proto_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_message_proto_v1_message_proto_rawDesc), len(file_internal_message_proto_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_message_proto_v1_message_proto_goTypes,
		DependencyIndexes: file_internal_message_proto_v1_message_proto_depIdxs,
		MessageInfos:      file_internal_message_proto_v1_message_proto_msgTypes,
	}.Build()
	File_internal_message_proto_v1_message_proto = out.File
	file_internal_message_proto_v1_message_proto_goTypes = nil
	file_internal_message_proto_v1_message_proto_depIdxs = nil
}
