// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/KimNattanan/go-chat-backend/internal/chat/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomRepo creates a new instance of MockRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepo {
	mock := &MockRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomRepo is an autogenerated mock type for the RoomRepo type
type MockRoomRepo struct {
	mock.Mock
}

type MockRoomRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepo) EXPECT() *MockRoomRepo_Expecter {
	return &MockRoomRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomRepo
func (_mock *MockRoomRepo) Create(ctx context.Context, room *entity.Room) error {
	ret := _mock.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Room) error); ok {
		r0 = returnFunc(ctx, room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *entity.Room
func (_e *MockRoomRepo_Expecter) Create(ctx interface{}, room interface{}) *MockRoomRepo_Create_Call {
	return &MockRoomRepo_Create_Call{Call: _e.mock.On("Create", ctx, room)}
}

func (_c *MockRoomRepo_Create_Call) Run(run func(ctx context.Context, room *entity.Room)) *MockRoomRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Room
		if args[1] != nil {
			arg1 = args[1].(*entity.Room)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepo_Create_Call) Return(err error) *MockRoomRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepo_Create_Call) RunAndReturn(run func(ctx context.Context, room *entity.Room) error) *MockRoomRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRoomRepo
func (_mock *MockRoomRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoomRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoomRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockRoomRepo_Delete_Call {
	return &MockRoomRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoomRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoomRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepo_Delete_Call) Return(err error) *MockRoomRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRoomRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockRoomRepo
func (_mock *MockRoomRepo) FindByID(ctx context.Context, id string) (*entity.Room, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Room, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Room); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoomRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoomRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoomRepo_FindByID_Call {
	return &MockRoomRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoomRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRoomRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepo_FindByID_Call) Return(room *entity.Room, err error) *MockRoomRepo_FindByID_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Room, error)) *MockRoomRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockRoomRepo
func (_mock *MockRoomRepo) FindByUserID(ctx context.Context, userID string) ([]*entity.Room, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Room, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Room); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockRoomRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRoomRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockRoomRepo_FindByUserID_Call {
	return &MockRoomRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockRoomRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRoomRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomRepo_FindByUserID_Call) Return(rooms []*entity.Room, err error) *MockRoomRepo_FindByUserID_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomRepo_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Room, error)) *MockRoomRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockRoomRepo
func (_mock *MockRoomRepo) Patch(ctx context.Context, id string, room *entity.Room) error {
	ret := _mock.Called(ctx, id, room)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *entity.Room) error); ok {
		r0 = returnFunc(ctx, id, room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomRepo_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockRoomRepo_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - room *entity.Room
func (_e *MockRoomRepo_Expecter) Patch(ctx interface{}, id interface{}, room interface{}) *MockRoomRepo_Patch_Call {
	return &MockRoomRepo_Patch_Call{Call: _e.mock.On("Patch", ctx, id, room)}
}

func (_c *MockRoomRepo_Patch_Call) Run(run func(ctx context.Context, id string, room *entity.Room)) *MockRoomRepo_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *entity.Room
		if args[2] != nil {
			arg2 = args[2].(*entity.Room)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoomRepo_Patch_Call) Return(err error) *MockRoomRepo_Patch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomRepo_Patch_Call) RunAndReturn(run func(ctx context.Context, id string, room *entity.Room) error) *MockRoomRepo_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMembershipRepo creates a new instance of MockMembershipRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMembershipRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMembershipRepo {
	mock := &MockMembershipRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMembershipRepo is an autogenerated mock type for the MembershipRepo type
type MockMembershipRepo struct {
	mock.Mock
}

type MockMembershipRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMembershipRepo) EXPECT() *MockMembershipRepo_Expecter {
	return &MockMembershipRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMembershipRepo
func (_mock *MockMembershipRepo) Create(ctx context.Context, membership *entity.Membership) error {
	ret := _mock.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Membership) error); ok {
		r0 = returnFunc(ctx, membership)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMembershipRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMembershipRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - membership *entity.Membership
func (_e *MockMembershipRepo_Expecter) Create(ctx interface{}, membership interface{}) *MockMembershipRepo_Create_Call {
	return &MockMembershipRepo_Create_Call{Call: _e.mock.On("Create", ctx, membership)}
}

func (_c *MockMembershipRepo_Create_Call) Run(run func(ctx context.Context, membership *entity.Membership)) *MockMembershipRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Membership
		if args[1] != nil {
			arg1 = args[1].(*entity.Membership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMembershipRepo_Create_Call) Return(err error) *MockMembershipRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMembershipRepo_Create_Call) RunAndReturn(run func(ctx context.Context, membership *entity.Membership) error) *MockMembershipRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMembershipRepo
func (_mock *MockMembershipRepo) Delete(ctx context.Context, roomID string, userID string) error {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMembershipRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMembershipRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockMembershipRepo_Expecter) Delete(ctx interface{}, roomID interface{}, userID interface{}) *MockMembershipRepo_Delete_Call {
	return &MockMembershipRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, roomID, userID)}
}

func (_c *MockMembershipRepo_Delete_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockMembershipRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMembershipRepo_Delete_Call) Return(err error) *MockMembershipRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMembershipRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, roomID string, userID string) error) *MockMembershipRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type MockMembershipRepo
func (_mock *MockMembershipRepo) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMembershipRepo_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockMembershipRepo_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMembershipRepo_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockMembershipRepo_DeleteByUserID_Call {
	return &MockMembershipRepo_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockMembershipRepo_DeleteByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockMembershipRepo_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMembershipRepo_DeleteByUserID_Call) Return(err error) *MockMembershipRepo_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMembershipRepo_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockMembershipRepo_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoomID provides a mock function for the type MockMembershipRepo
func (_mock *MockMembershipRepo) FindByRoomID(ctx context.Context, roomID string) ([]*entity.Membership, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoomID")
	}

	var r0 []*entity.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Membership, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Membership); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMembershipRepo_FindByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoomID'
type MockMembershipRepo_FindByRoomID_Call struct {
	*mock.Call
}

// FindByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockMembershipRepo_Expecter) FindByRoomID(ctx interface{}, roomID interface{}) *MockMembershipRepo_FindByRoomID_Call {
	return &MockMembershipRepo_FindByRoomID_Call{Call: _e.mock.On("FindByRoomID", ctx, roomID)}
}

func (_c *MockMembershipRepo_FindByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockMembershipRepo_FindByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMembershipRepo_FindByRoomID_Call) Return(memberships []*entity.Membership, err error) *MockMembershipRepo_FindByRoomID_Call {
	_c.Call.Return(memberships, err)
	return _c
}

func (_c *MockMembershipRepo_FindByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) ([]*entity.Membership, error)) *MockMembershipRepo_FindByRoomID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRoomIDAndUserID provides a mock function for the type MockMembershipRepo
func (_mock *MockMembershipRepo) FindByRoomIDAndUserID(ctx context.Context, roomID string, userID string) (*entity.Membership, error) {
	ret := _mock.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByRoomIDAndUserID")
	}

	var r0 *entity.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Membership, error)); ok {
		return returnFunc(ctx, roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.Membership); ok {
		r0 = returnFunc(ctx, roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMembershipRepo_FindByRoomIDAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRoomIDAndUserID'
type MockMembershipRepo_FindByRoomIDAndUserID_Call struct {
	*mock.Call
}

// FindByRoomIDAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - userID string
func (_e *MockMembershipRepo_Expecter) FindByRoomIDAndUserID(ctx interface{}, roomID interface{}, userID interface{}) *MockMembershipRepo_FindByRoomIDAndUserID_Call {
	return &MockMembershipRepo_FindByRoomIDAndUserID_Call{Call: _e.mock.On("FindByRoomIDAndUserID", ctx, roomID, userID)}
}

func (_c *MockMembershipRepo_FindByRoomIDAndUserID_Call) Run(run func(ctx context.Context, roomID string, userID string)) *MockMembershipRepo_FindByRoomIDAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMembershipRepo_FindByRoomIDAndUserID_Call) Return(membership *entity.Membership, err error) *MockMembershipRepo_FindByRoomIDAndUserID_Call {
	_c.Call.Return(membership, err)
	return _c
}

func (_c *MockMembershipRepo_FindByRoomIDAndUserID_Call) RunAndReturn(run func(ctx context.Context, roomID string, userID string) (*entity.Membership, error)) *MockMembershipRepo_FindByRoomIDAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockMembershipRepo
func (_mock *MockMembershipRepo) FindByUserID(ctx context.Context, userID string) ([]*entity.Membership, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Membership
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Membership, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Membership); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Membership)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMembershipRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockMembershipRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMembershipRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockMembershipRepo_FindByUserID_Call {
	return &MockMembershipRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockMembershipRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockMembershipRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMembershipRepo_FindByUserID_Call) Return(memberships []*entity.Membership, err error) *MockMembershipRepo_FindByUserID_Call {
	_c.Call.Return(memberships, err)
	return _c
}

func (_c *MockMembershipRepo_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Membership, error)) *MockMembershipRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}
