// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/KimNattanan/go-chat-backend/internal/auth/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Create(ctx context.Context, user *entity.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepo_Create_Call {
	return &MockUserRepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepo_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Create_Call) Return(err error) *MockUserRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) error) *MockUserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockUserRepo_Delete_Call {
	return &MockUserRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Delete_Call) Return(err error) *MockUserRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepo_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepo_FindByEmail_Call {
	return &MockUserRepo_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepo_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) Return(user *entity.User, err error) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entity.User, error)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByID(ctx context.Context, id string) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepo_FindByID_Call {
	return &MockUserRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByID_Call) Return(user *entity.User, err error) *MockUserRepo_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.User, error)) *MockUserRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepo creates a new instance of MockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepo {
	mock := &MockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepo is an autogenerated mock type for the SessionRepo type
type MockSessionRepo struct {
	mock.Mock
}

type MockSessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepo) EXPECT() *MockSessionRepo_Expecter {
	return &MockSessionRepo_Expecter{mock: &_m.Mock}
}

// AcquireRefreshLock provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) AcquireRefreshLock(ctx context.Context, sessionID string, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, sessionID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AcquireRefreshLock")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, sessionID, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, sessionID, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, sessionID, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_AcquireRefreshLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireRefreshLock'
type MockSessionRepo_AcquireRefreshLock_Call struct {
	*mock.Call
}

// AcquireRefreshLock is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - ttl time.Duration
func (_e *MockSessionRepo_Expecter) AcquireRefreshLock(ctx interface{}, sessionID interface{}, ttl interface{}) *MockSessionRepo_AcquireRefreshLock_Call {
	return &MockSessionRepo_AcquireRefreshLock_Call{Call: _e.mock.On("AcquireRefreshLock", ctx, sessionID, ttl)}
}

func (_c *MockSessionRepo_AcquireRefreshLock_Call) Run(run func(ctx context.Context, sessionID string, ttl time.Duration)) *MockSessionRepo_AcquireRefreshLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepo_AcquireRefreshLock_Call) Return(b bool, err error) *MockSessionRepo_AcquireRefreshLock_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionRepo_AcquireRefreshLock_Call) RunAndReturn(run func(ctx context.Context, sessionID string, ttl time.Duration) (bool, error)) *MockSessionRepo_AcquireRefreshLock_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Create(ctx context.Context, session *entity.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.Session
func (_e *MockSessionRepo_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepo_Create_Call {
	return &MockSessionRepo_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepo_Create_Call) Run(run func(ctx context.Context, session *entity.Session)) *MockSessionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Session
		if args[1] != nil {
			arg1 = args[1].(*entity.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Create_Call) Return(err error) *MockSessionRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, session *entity.Session) error) *MockSessionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockSessionRepo_Delete_Call {
	return &MockSessionRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSessionRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Delete_Call) Return(err error) *MockSessionRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockSessionRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DenylistAccessToken provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) DenylistAccessToken(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _mock.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for DenylistAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_DenylistAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DenylistAccessToken'
type MockSessionRepo_DenylistAccessToken_Call struct {
	*mock.Call
}

// DenylistAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockSessionRepo_Expecter) DenylistAccessToken(ctx interface{}, jti interface{}, ttl interface{}) *MockSessionRepo_DenylistAccessToken_Call {
	return &MockSessionRepo_DenylistAccessToken_Call{Call: _e.mock.On("DenylistAccessToken", ctx, jti, ttl)}
}

func (_c *MockSessionRepo_DenylistAccessToken_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockSessionRepo_DenylistAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepo_DenylistAccessToken_Call) Return(err error) *MockSessionRepo_DenylistAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_DenylistAccessToken_Call) RunAndReturn(run func(ctx context.Context, jti string, ttl time.Duration) error) *MockSessionRepo_DenylistAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) FindByID(ctx context.Context, id string) (*entity.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSessionRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockSessionRepo_FindByID_Call {
	return &MockSessionRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSessionRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_FindByID_Call) Return(session *entity.Session, err error) *MockSessionRepo_FindByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Session, error)) *MockSessionRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) FindByUserID(ctx context.Context, userID string) ([]*entity.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockSessionRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockSessionRepo_FindByUserID_Call {
	return &MockSessionRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockSessionRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockSessionRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_FindByUserID_Call) Return(sessions []*entity.Session, err error) *MockSessionRepo_FindByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepo_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Session, error)) *MockSessionRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindRefreshGrace provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) FindRefreshGrace(ctx context.Context, oldSessionID string) (*entity.RefreshGrace, error) {
	ret := _mock.Called(ctx, oldSessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindRefreshGrace")
	}

	var r0 *entity.RefreshGrace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.RefreshGrace, error)); ok {
		return returnFunc(ctx, oldSessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.RefreshGrace); ok {
		r0 = returnFunc(ctx, oldSessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RefreshGrace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, oldSessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_FindRefreshGrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRefreshGrace'
type MockSessionRepo_FindRefreshGrace_Call struct {
	*mock.Call
}

// FindRefreshGrace is a helper method to define mock.On call
//   - ctx context.Context
//   - oldSessionID string
func (_e *MockSessionRepo_Expecter) FindRefreshGrace(ctx interface{}, oldSessionID interface{}) *MockSessionRepo_FindRefreshGrace_Call {
	return &MockSessionRepo_FindRefreshGrace_Call{Call: _e.mock.On("FindRefreshGrace", ctx, oldSessionID)}
}

func (_c *MockSessionRepo_FindRefreshGrace_Call) Run(run func(ctx context.Context, oldSessionID string)) *MockSessionRepo_FindRefreshGrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_FindRefreshGrace_Call) Return(refreshGrace *entity.RefreshGrace, err error) *MockSessionRepo_FindRefreshGrace_Call {
	_c.Call.Return(refreshGrace, err)
	return _c
}

func (_c *MockSessionRepo_FindRefreshGrace_Call) RunAndReturn(run func(ctx context.Context, oldSessionID string) (*entity.RefreshGrace, error)) *MockSessionRepo_FindRefreshGrace_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateUserAccessTokens provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) InvalidateUserAccessTokens(ctx context.Context, userID string, ttl time.Duration) error {
	ret := _mock.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateUserAccessTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_InvalidateUserAccessTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserAccessTokens'
type MockSessionRepo_InvalidateUserAccessTokens_Call struct {
	*mock.Call
}

// InvalidateUserAccessTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - ttl time.Duration
func (_e *MockSessionRepo_Expecter) InvalidateUserAccessTokens(ctx interface{}, userID interface{}, ttl interface{}) *MockSessionRepo_InvalidateUserAccessTokens_Call {
	return &MockSessionRepo_InvalidateUserAccessTokens_Call{Call: _e.mock.On("InvalidateUserAccessTokens", ctx, userID, ttl)}
}

func (_c *MockSessionRepo_InvalidateUserAccessTokens_Call) Run(run func(ctx context.Context, userID string, ttl time.Duration)) *MockSessionRepo_InvalidateUserAccessTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepo_InvalidateUserAccessTokens_Call) Return(err error) *MockSessionRepo_InvalidateUserAccessTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_InvalidateUserAccessTokens_Call) RunAndReturn(run func(ctx context.Context, userID string, ttl time.Duration) error) *MockSessionRepo_InvalidateUserAccessTokens_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccessRevoked provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) IsAccessRevoked(ctx context.Context, jti string, userID string, issuedAt time.Time) (bool, error) {
	ret := _mock.Called(ctx, jti, userID, issuedAt)

	if len(ret) == 0 {
		panic("no return value specified for IsAccessRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (bool, error)); ok {
		return returnFunc(ctx, jti, userID, issuedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) bool); ok {
		r0 = returnFunc(ctx, jti, userID, issuedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, jti, userID, issuedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_IsAccessRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccessRevoked'
type MockSessionRepo_IsAccessRevoked_Call struct {
	*mock.Call
}

// IsAccessRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - userID string
//   - issuedAt time.Time
func (_e *MockSessionRepo_Expecter) IsAccessRevoked(ctx interface{}, jti interface{}, userID interface{}, issuedAt interface{}) *MockSessionRepo_IsAccessRevoked_Call {
	return &MockSessionRepo_IsAccessRevoked_Call{Call: _e.mock.On("IsAccessRevoked", ctx, jti, userID, issuedAt)}
}

func (_c *MockSessionRepo_IsAccessRevoked_Call) Run(run func(ctx context.Context, jti string, userID string, issuedAt time.Time)) *MockSessionRepo_IsAccessRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepo_IsAccessRevoked_Call) Return(b bool, err error) *MockSessionRepo_IsAccessRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionRepo_IsAccessRevoked_Call) RunAndReturn(run func(ctx context.Context, jti string, userID string, issuedAt time.Time) (bool, error)) *MockSessionRepo_IsAccessRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseRefreshLock provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) ReleaseRefreshLock(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseRefreshLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_ReleaseRefreshLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseRefreshLock'
type MockSessionRepo_ReleaseRefreshLock_Call struct {
	*mock.Call
}

// ReleaseRefreshLock is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepo_Expecter) ReleaseRefreshLock(ctx interface{}, sessionID interface{}) *MockSessionRepo_ReleaseRefreshLock_Call {
	return &MockSessionRepo_ReleaseRefreshLock_Call{Call: _e.mock.On("ReleaseRefreshLock", ctx, sessionID)}
}

func (_c *MockSessionRepo_ReleaseRefreshLock_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepo_ReleaseRefreshLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_ReleaseRefreshLock_Call) Return(err error) *MockSessionRepo_ReleaseRefreshLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_ReleaseRefreshLock_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionRepo_ReleaseRefreshLock_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Revoke(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSessionRepo_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepo_Expecter) Revoke(ctx interface{}, id interface{}) *MockSessionRepo_Revoke_Call {
	return &MockSessionRepo_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockSessionRepo_Revoke_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepo_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Revoke_Call) Return(err error) *MockSessionRepo_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Revoke_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockSessionRepo_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserID provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) RevokeAllByUserID(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_RevokeAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserID'
type MockSessionRepo_RevokeAllByUserID_Call struct {
	*mock.Call
}

// RevokeAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionRepo_Expecter) RevokeAllByUserID(ctx interface{}, userID interface{}) *MockSessionRepo_RevokeAllByUserID_Call {
	return &MockSessionRepo_RevokeAllByUserID_Call{Call: _e.mock.On("RevokeAllByUserID", ctx, userID)}
}

func (_c *MockSessionRepo_RevokeAllByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockSessionRepo_RevokeAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_RevokeAllByUserID_Call) Return(err error) *MockSessionRepo_RevokeAllByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_RevokeAllByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockSessionRepo_RevokeAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshGrace provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) SaveRefreshGrace(ctx context.Context, oldSessionID string, grace *entity.RefreshGrace, ttl time.Duration) error {
	ret := _mock.Called(ctx, oldSessionID, grace, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshGrace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *entity.RefreshGrace, time.Duration) error); ok {
		r0 = returnFunc(ctx, oldSessionID, grace, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_SaveRefreshGrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshGrace'
type MockSessionRepo_SaveRefreshGrace_Call struct {
	*mock.Call
}

// SaveRefreshGrace is a helper method to define mock.On call
//   - ctx context.Context
//   - oldSessionID string
//   - grace *entity.RefreshGrace
//   - ttl time.Duration
func (_e *MockSessionRepo_Expecter) SaveRefreshGrace(ctx interface{}, oldSessionID interface{}, grace interface{}, ttl interface{}) *MockSessionRepo_SaveRefreshGrace_Call {
	return &MockSessionRepo_SaveRefreshGrace_Call{Call: _e.mock.On("SaveRefreshGrace", ctx, oldSessionID, grace, ttl)}
}

func (_c *MockSessionRepo_SaveRefreshGrace_Call) Run(run func(ctx context.Context, oldSessionID string, grace *entity.RefreshGrace, ttl time.Duration)) *MockSessionRepo_SaveRefreshGrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *entity.RefreshGrace
		if args[2] != nil {
			arg2 = args[2].(*entity.RefreshGrace)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSessionRepo_SaveRefreshGrace_Call) Return(err error) *MockSessionRepo_SaveRefreshGrace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_SaveRefreshGrace_Call) RunAndReturn(run func(ctx context.Context, oldSessionID string, grace *entity.RefreshGrace, ttl time.Duration) error) *MockSessionRepo_SaveRefreshGrace_Call {
	_c.Call.Return(run)
	return _c
}
