// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/KimNattanan/go-chat-backend/internal/auth/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Create(ctx context.Context, user *entity.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepo_Create_Call {
	return &MockUserRepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepo_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Create_Call) Return(err error) *MockUserRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) error) *MockUserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockUserRepo_Delete_Call {
	return &MockUserRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Delete_Call) Return(err error) *MockUserRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepo_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepo_FindByEmail_Call {
	return &MockUserRepo_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepo_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) Return(user *entity.User, err error) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entity.User, error)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) FindByID(ctx context.Context, id string) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepo_FindByID_Call {
	return &MockUserRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_FindByID_Call) Return(user *entity.User, err error) *MockUserRepo_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.User, error)) *MockUserRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRepo creates a new instance of MockSessionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepo {
	mock := &MockSessionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepo is an autogenerated mock type for the SessionRepo type
type MockSessionRepo struct {
	mock.Mock
}

type MockSessionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepo) EXPECT() *MockSessionRepo_Expecter {
	return &MockSessionRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Create(ctx context.Context, session *entity.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.Session
func (_e *MockSessionRepo_Expecter) Create(ctx interface{}, session interface{}) *MockSessionRepo_Create_Call {
	return &MockSessionRepo_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepo_Create_Call) Run(run func(ctx context.Context, session *entity.Session)) *MockSessionRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Session
		if args[1] != nil {
			arg1 = args[1].(*entity.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Create_Call) Return(err error) *MockSessionRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Create_Call) RunAndReturn(run func(ctx context.Context, session *entity.Session) error) *MockSessionRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockSessionRepo_Delete_Call {
	return &MockSessionRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSessionRepo_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Delete_Call) Return(err error) *MockSessionRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockSessionRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) FindByID(ctx context.Context, id string) (*entity.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSessionRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockSessionRepo_FindByID_Call {
	return &MockSessionRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSessionRepo_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_FindByID_Call) Return(session *entity.Session, err error) *MockSessionRepo_FindByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepo_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*entity.Session, error)) *MockSessionRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) FindByUserID(ctx context.Context, userID string) ([]*entity.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*entity.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepo_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockSessionRepo_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionRepo_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockSessionRepo_FindByUserID_Call {
	return &MockSessionRepo_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockSessionRepo_FindByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockSessionRepo_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_FindByUserID_Call) Return(sessions []*entity.Session, err error) *MockSessionRepo_FindByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepo_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Session, error)) *MockSessionRepo_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockSessionRepo
func (_mock *MockSessionRepo) Revoke(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepo_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSessionRepo_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSessionRepo_Expecter) Revoke(ctx interface{}, id interface{}) *MockSessionRepo_Revoke_Call {
	return &MockSessionRepo_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockSessionRepo_Revoke_Call) Run(run func(ctx context.Context, id string)) *MockSessionRepo_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepo_Revoke_Call) Return(err error) *MockSessionRepo_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepo_Revoke_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockSessionRepo_Revoke_Call {
	_c.Call.Return(run)
	return _c
}
