// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/chat/proto/v1/membership.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FindMembershipsByRoomIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMembershipsByRoomIDRequest) Reset() {
	*x = FindMembershipsByRoomIDRequest{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMembershipsByRoomIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMembershipsByRoomIDRequest) ProtoMessage() {}

func (x *FindMembershipsByRoomIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMembershipsByRoomIDRequest.ProtoReflect.Descriptor instead.
func (*FindMembershipsByRoomIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{1}
}

func (x *FindMembershipsByRoomIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type FindMembershipsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMembershipsByUserIDRequest) Reset() {
	*x = FindMembershipsByUserIDRequest{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMembershipsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMembershipsByUserIDRequest) ProtoMessage() {}

func (x *FindMembershipsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMembershipsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindMembershipsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{2}
}

func (x *FindMembershipsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindMembershipByRoomIDAndUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMembershipByRoomIDAndUserIDRequest) Reset() {
	*x = FindMembershipByRoomIDAndUserIDRequest{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMembershipByRoomIDAndUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMembershipByRoomIDAndUserIDRequest) ProtoMessage() {}

func (x *FindMembershipByRoomIDAndUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMembershipByRoomIDAndUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindMembershipByRoomIDAndUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{3}
}

func (x *FindMembershipByRoomIDAndUserIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *FindMembershipByRoomIDAndUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMembershipRequest) Reset() {
	*x = CreateMembershipRequest{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRequest) ProtoMessage() {}

func (x *CreateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMembershipRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMembershipsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipsByUserIDRequest) Reset() {
	*x = DeleteMembershipsByUserIDRequest{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipsByUserIDRequest) ProtoMessage() {}

func (x *DeleteMembershipsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteMembershipsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMembershipsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMembershipByRoomIDAndUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipByRoomIDAndUserIDRequest) Reset() {
	*x = DeleteMembershipByRoomIDAndUserIDRequest{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipByRoomIDAndUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipByRoomIDAndUserIDRequest) ProtoMessage() {}

func (x *DeleteMembershipByRoomIDAndUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipByRoomIDAndUserIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteMembershipByRoomIDAndUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMembershipByRoomIDAndUserIDRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DeleteMembershipByRoomIDAndUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    *Membership            `protobuf:"bytes,1,opt,name=Membership,proto3" json:"Membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipResponse) Reset() {
	*x = MembershipResponse{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipResponse) ProtoMessage() {}

func (x *MembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipResponse.ProtoReflect.Descriptor instead.
func (*MembershipResponse) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{7}
}

func (x *MembershipResponse) GetMembership() *Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

type MembershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Membership    []*Membership          `protobuf:"bytes,1,rep,name=Membership,proto3" json:"Membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipsResponse) Reset() {
	*x = MembershipsResponse{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipsResponse) ProtoMessage() {}

func (x *MembershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipsResponse.ProtoReflect.Descriptor instead.
func (*MembershipsResponse) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{8}
}

func (x *MembershipsResponse) GetMembership() []*Membership {
	if x != nil {
		return x.Membership
	}
	return nil
}

type DeleteMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMembershipResponse) Reset() {
	*x = DeleteMembershipResponse{}
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMembershipResponse) ProtoMessage() {}

func (x *DeleteMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMembershipResponse.ProtoReflect.Descriptor instead.
func (*DeleteMembershipResponse) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_membership_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMembershipResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_chat_proto_v1_membership_proto protoreflect.FileDescriptor

const file_internal_chat_proto_v1_membership_proto_rawDesc = "" +
	"\n" +
	"'internal/chat/proto/v1/membership.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\n" +
	"Membership\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\x1eFindMembershipsByRoomIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"9\n" +
	"\x1eFindMembershipsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"&FindMembershipByRoomIDAndUserIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x17CreateMembershipRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	" DeleteMembershipsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\\\n" +
	"(DeleteMembershipByRoomIDAndUserIDRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x12MembershipResponse\x123\n" +
	"\n" +
	"Membership\x18\x01 \x01(\v2\x13.chat.v1.MembershipR\n" +
	"Membership\"J\n" +
	"\x13MembershipsResponse\x123\n" +
	"\n" +
	"Membership\x18\x01 \x03(\v2\x13.chat.v1.MembershipR\n" +
	"Membership\"4\n" +
	"\x18DeleteMembershipResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x81\x05\n" +
	"\x11MembershipService\x12`\n" +
	"\x17FindMembershipsByRoomID\x12'.chat.v1.FindMembershipsByRoomIDRequest\x1a\x1c.chat.v1.MembershipsResponse\x12`\n" +
	"\x17FindMembershipsByUserID\x12'.chat.v1.FindMembershipsByUserIDRequest\x1a\x1c.chat.v1.MembershipsResponse\x12o\n" +
	"\x1fFindMembershipByRoomIDAndUserID\x12/.chat.v1.FindMembershipByRoomIDAndUserIDRequest\x1a\x1b.chat.v1.MembershipResponse\x12Q\n" +
	"\x10CreateMembership\x12 .chat.v1.CreateMembershipRequest\x1a\x1b.chat.v1.MembershipResponse\x12i\n" +
	"\x19DeleteMembershipsByUserID\x12).chat.v1.DeleteMembershipsByUserIDRequest\x1a!.chat.v1.DeleteMembershipResponse\x12y\n" +
	"!DeleteMembershipByRoomIDAndUserID\x121.chat.v1.DeleteMembershipByRoomIDAndUserIDRequest\x1a!.chat.v1.DeleteMembershipResponseB\x18Z\x16internal/chat/proto/v1b\x06proto3"

var (
	file_internal_chat_proto_v1_membership_proto_rawDescOnce sync.Once
	file_internal_chat_proto_v1_membership_proto_rawDescData []byte
)

func file_internal_chat_proto_v1_membership_proto_rawDescGZIP() []byte {
	file_internal_chat_proto_v1_membership_proto_rawDescOnce.Do(func() {
		file_internal_chat_proto_v1_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_chat_proto_v1_membership_proto_rawDesc), len(file_internal_chat_proto_v1_membership_proto_rawDesc)))
	})
	return file_internal_chat_proto_v1_membership_proto_rawDescData
}

var file_internal_chat_proto_v1_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_chat_proto_v1_membership_proto_goTypes = []any{
	(*Membership)(nil),                               // 0: chat.v1.Membership
	(*FindMembershipsByRoomIDRequest)(nil),           // 1: chat.v1.FindMembershipsByRoomIDRequest
	(*FindMembershipsByUserIDRequest)(nil),           // 2: chat.v1.FindMembershipsByUserIDRequest
	(*FindMembershipByRoomIDAndUserIDRequest)(nil),   // 3: chat.v1.FindMembershipByRoomIDAndUserIDRequest
	(*CreateMembershipRequest)(nil),                  // 4: chat.v1.CreateMembershipRequest
	(*DeleteMembershipsByUserIDRequest)(nil),         // 5: chat.v1.DeleteMembershipsByUserIDRequest
	(*DeleteMembershipByRoomIDAndUserIDRequest)(nil), // 6: chat.v1.DeleteMembershipByRoomIDAndUserIDRequest
	(*MembershipResponse)(nil),                       // 7: chat.v1.MembershipResponse
	(*MembershipsResponse)(nil),                      // 8: chat.v1.MembershipsResponse
	(*DeleteMembershipResponse)(nil),                 // 9: chat.v1.DeleteMembershipResponse
	(*timestamppb.Timestamp)(nil),                    // 10: google.protobuf.Timestamp
}
var file_internal_chat_proto_v1_membership_proto_depIdxs = []int32{
	10, // 0: chat.v1.Membership.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: chat.v1.MembershipResponse.Membership:type_name -> chat.v1.Membership
	0,  // 2: chat.v1.MembershipsResponse.Membership:type_name -> chat.v1.Membership
	1,  // 3: chat.v1.MembershipService.FindMembershipsByRoomID:input_type -> chat.v1.FindMembershipsByRoomIDRequest
	2,  // 4: chat.v1.MembershipService.FindMembershipsByUserID:input_type -> chat.v1.FindMembershipsByUserIDRequest
	3,  // 5: chat.v1.MembershipService.FindMembershipByRoomIDAndUserID:input_type -> chat.v1.FindMembershipByRoomIDAndUserIDRequest
	4,  // 6: chat.v1.MembershipService.CreateMembership:input_type -> chat.v1.CreateMembershipRequest
	5,  // 7: chat.v1.MembershipService.DeleteMembershipsByUserID:input_type -> chat.v1.DeleteMembershipsByUserIDRequest
	6,  // 8: chat.v1.MembershipService.DeleteMembershipByRoomIDAndUserID:input_type -> chat.v1.DeleteMembershipByRoomIDAndUserIDRequest
	8,  // 9: chat.v1.MembershipService.FindMembershipsByRoomID:output_type -> chat.v1.MembershipsResponse
	8,  // 10: chat.v1.MembershipService.FindMembershipsByUserID:output_type -> chat.v1.MembershipsResponse
	7,  // 11: chat.v1.MembershipService.FindMembershipByRoomIDAndUserID:output_type -> chat.v1.MembershipResponse
	7,  // 12: chat.v1.MembershipService.CreateMembership:output_type -> chat.v1.MembershipResponse
	9,  // 13: chat.v1.MembershipService.DeleteMembershipsByUserID:output_type -> chat.v1.DeleteMembershipResponse
	9,  // 14: chat.v1.MembershipService.DeleteMembershipByRoomIDAndUserID:output_type -> chat.v1.DeleteMembershipResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_chat_proto_v1_membership_proto_init() }
func file_internal_chat_proto_v1_membership_proto_init() {
	if File_internal_chat_proto_v1_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_chat_proto_v1_membership_proto_rawDesc), len(file_internal_chat_proto_v1_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_chat_proto_v1_membership_proto_goTypes,
		DependencyIndexes: file_internal_chat_proto_v1_membership_proto_depIdxs,
		MessageInfos:      file_internal_chat_proto_v1_membership_proto_msgTypes,
	}.Build()
	File_internal_chat_proto_v1_membership_proto = out.File
	file_internal_chat_proto_v1_membership_proto_goTypes = nil
	file_internal_chat_proto_v1_membership_proto_depIdxs = nil
}
