// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/chat/proto/v1/membership.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipService_FindMembershipsByRoomID_FullMethodName           = "/chat.v1.MembershipService/FindMembershipsByRoomID"
	MembershipService_FindMembershipsByUserID_FullMethodName           = "/chat.v1.MembershipService/FindMembershipsByUserID"
	MembershipService_FindMembershipByRoomIDAndUserID_FullMethodName   = "/chat.v1.MembershipService/FindMembershipByRoomIDAndUserID"
	MembershipService_CreateMembership_FullMethodName                  = "/chat.v1.MembershipService/CreateMembership"
	MembershipService_DeleteMembershipsByUserID_FullMethodName         = "/chat.v1.MembershipService/DeleteMembershipsByUserID"
	MembershipService_DeleteMembershipByRoomIDAndUserID_FullMethodName = "/chat.v1.MembershipService/DeleteMembershipByRoomIDAndUserID"
)

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembershipServiceClient interface {
	FindMembershipsByRoomID(ctx context.Context, in *FindMembershipsByRoomIDRequest, opts ...grpc.CallOption) (*MembershipsResponse, error)
	FindMembershipsByUserID(ctx context.Context, in *FindMembershipsByUserIDRequest, opts ...grpc.CallOption) (*MembershipsResponse, error)
	FindMembershipByRoomIDAndUserID(ctx context.Context, in *FindMembershipByRoomIDAndUserIDRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	CreateMembership(ctx context.Context, in *CreateMembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	DeleteMembershipsByUserID(ctx context.Context, in *DeleteMembershipsByUserIDRequest, opts ...grpc.CallOption) (*DeleteMembershipResponse, error)
	DeleteMembershipByRoomIDAndUserID(ctx context.Context, in *DeleteMembershipByRoomIDAndUserIDRequest, opts ...grpc.CallOption) (*DeleteMembershipResponse, error)
}

type membershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipServiceClient(cc grpc.ClientConnInterface) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) FindMembershipsByRoomID(ctx context.Context, in *FindMembershipsByRoomIDRequest, opts ...grpc.CallOption) (*MembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipsResponse)
	err := c.cc.Invoke(ctx, MembershipService_FindMembershipsByRoomID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) FindMembershipsByUserID(ctx context.Context, in *FindMembershipsByUserIDRequest, opts ...grpc.CallOption) (*MembershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipsResponse)
	err := c.cc.Invoke(ctx, MembershipService_FindMembershipsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) FindMembershipByRoomIDAndUserID(ctx context.Context, in *FindMembershipByRoomIDAndUserIDRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_FindMembershipByRoomIDAndUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CreateMembership(ctx context.Context, in *CreateMembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_CreateMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) DeleteMembershipsByUserID(ctx context.Context, in *DeleteMembershipsByUserIDRequest, opts ...grpc.CallOption) (*DeleteMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_DeleteMembershipsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) DeleteMembershipByRoomIDAndUserID(ctx context.Context, in *DeleteMembershipByRoomIDAndUserIDRequest, opts ...grpc.CallOption) (*DeleteMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_DeleteMembershipByRoomIDAndUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
// All implementations must embed UnimplementedMembershipServiceServer
// for forward compatibility.
type MembershipServiceServer interface {
	FindMembershipsByRoomID(context.Context, *FindMembershipsByRoomIDRequest) (*MembershipsResponse, error)
	FindMembershipsByUserID(context.Context, *FindMembershipsByUserIDRequest) (*MembershipsResponse, error)
	FindMembershipByRoomIDAndUserID(context.Context, *FindMembershipByRoomIDAndUserIDRequest) (*MembershipResponse, error)
	CreateMembership(context.Context, *CreateMembershipRequest) (*MembershipResponse, error)
	DeleteMembershipsByUserID(context.Context, *DeleteMembershipsByUserIDRequest) (*DeleteMembershipResponse, error)
	DeleteMembershipByRoomIDAndUserID(context.Context, *DeleteMembershipByRoomIDAndUserIDRequest) (*DeleteMembershipResponse, error)
	mustEmbedUnimplementedMembershipServiceServer()
}

// UnimplementedMembershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServiceServer struct{}

func (UnimplementedMembershipServiceServer) FindMembershipsByRoomID(context.Context, *FindMembershipsByRoomIDRequest) (*MembershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMembershipsByRoomID not implemented")
}
func (UnimplementedMembershipServiceServer) FindMembershipsByUserID(context.Context, *FindMembershipsByUserIDRequest) (*MembershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMembershipsByUserID not implemented")
}
func (UnimplementedMembershipServiceServer) FindMembershipByRoomIDAndUserID(context.Context, *FindMembershipByRoomIDAndUserIDRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindMembershipByRoomIDAndUserID not implemented")
}
func (UnimplementedMembershipServiceServer) CreateMembership(context.Context, *CreateMembershipRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMembership not implemented")
}
func (UnimplementedMembershipServiceServer) DeleteMembershipsByUserID(context.Context, *DeleteMembershipsByUserIDRequest) (*DeleteMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMembershipsByUserID not implemented")
}
func (UnimplementedMembershipServiceServer) DeleteMembershipByRoomIDAndUserID(context.Context, *DeleteMembershipByRoomIDAndUserIDRequest) (*DeleteMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMembershipByRoomIDAndUserID not implemented")
}
func (UnimplementedMembershipServiceServer) mustEmbedUnimplementedMembershipServiceServer() {}
func (UnimplementedMembershipServiceServer) testEmbeddedByValue()                           {}

// UnsafeMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServiceServer will
// result in compilation errors.
type UnsafeMembershipServiceServer interface {
	mustEmbedUnimplementedMembershipServiceServer()
}

func RegisterMembershipServiceServer(s grpc.ServiceRegistrar, srv MembershipServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipService_ServiceDesc, srv)
}

func _MembershipService_FindMembershipsByRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMembershipsByRoomIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).FindMembershipsByRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_FindMembershipsByRoomID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).FindMembershipsByRoomID(ctx, req.(*FindMembershipsByRoomIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_FindMembershipsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMembershipsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).FindMembershipsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_FindMembershipsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).FindMembershipsByUserID(ctx, req.(*FindMembershipsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_FindMembershipByRoomIDAndUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindMembershipByRoomIDAndUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).FindMembershipByRoomIDAndUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_FindMembershipByRoomIDAndUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).FindMembershipByRoomIDAndUserID(ctx, req.(*FindMembershipByRoomIDAndUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CreateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CreateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CreateMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CreateMembership(ctx, req.(*CreateMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_DeleteMembershipsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMembershipsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).DeleteMembershipsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_DeleteMembershipsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).DeleteMembershipsByUserID(ctx, req.(*DeleteMembershipsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_DeleteMembershipByRoomIDAndUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMembershipByRoomIDAndUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).DeleteMembershipByRoomIDAndUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_DeleteMembershipByRoomIDAndUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).DeleteMembershipByRoomIDAndUserID(ctx, req.(*DeleteMembershipByRoomIDAndUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipService_ServiceDesc is the grpc.ServiceDesc for MembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMembershipsByRoomID",
			Handler:    _MembershipService_FindMembershipsByRoomID_Handler,
		},
		{
			MethodName: "FindMembershipsByUserID",
			Handler:    _MembershipService_FindMembershipsByUserID_Handler,
		},
		{
			MethodName: "FindMembershipByRoomIDAndUserID",
			Handler:    _MembershipService_FindMembershipByRoomIDAndUserID_Handler,
		},
		{
			MethodName: "CreateMembership",
			Handler:    _MembershipService_CreateMembership_Handler,
		},
		{
			MethodName: "DeleteMembershipsByUserID",
			Handler:    _MembershipService_DeleteMembershipsByUserID_Handler,
		},
		{
			MethodName: "DeleteMembershipByRoomIDAndUserID",
			Handler:    _MembershipService_DeleteMembershipByRoomIDAndUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/chat/proto/v1/membership.proto",
}
