// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/chat/proto/v1/room.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Memberships   []*Membership          `protobuf:"bytes,5,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Room) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type FindRoomByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRoomByIDRequest) Reset() {
	*x = FindRoomByIDRequest{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRoomByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoomByIDRequest) ProtoMessage() {}

func (x *FindRoomByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoomByIDRequest.ProtoReflect.Descriptor instead.
func (*FindRoomByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *FindRoomByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindRoomsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRoomsByUserIDRequest) Reset() {
	*x = FindRoomsByUserIDRequest{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRoomsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRoomsByUserIDRequest) ProtoMessage() {}

func (x *FindRoomsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRoomsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindRoomsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *FindRoomsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PatchRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRoomRequest) Reset() {
	*x = PatchRoomRequest{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoomRequest) ProtoMessage() {}

func (x *PatchRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoomRequest.ProtoReflect.Descriptor instead.
func (*PatchRoomRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *PatchRoomRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *RoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type RoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomsResponse) Reset() {
	*x = RoomsResponse{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomsResponse) ProtoMessage() {}

func (x *RoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomsResponse.ProtoReflect.Descriptor instead.
func (*RoomsResponse) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *RoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type DeleteRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomResponse) Reset() {
	*x = DeleteRoomResponse{}
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomResponse) ProtoMessage() {}

func (x *DeleteRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chat_proto_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return file_internal_chat_proto_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_chat_proto_v1_room_proto protoreflect.FileDescriptor

const file_internal_chat_proto_v1_room_proto_rawDesc = "" +
	"\n" +
	"!internal/chat/proto/v1/room.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x125\n" +
	"\vmemberships\x18\x05 \x03(\v2\x13.chat.v1.MembershipR\vmemberships\"`\n" +
	"\n" +
	"Membership\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"%\n" +
	"\x13FindRoomByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x18FindRoomsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\")\n" +
	"\x11CreateRoomRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"(\n" +
	"\x10PatchRoomRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"#\n" +
	"\x11DeleteRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\fRoomResponse\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.chat.v1.RoomR\x04room\"4\n" +
	"\rRoomsResponse\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.chat.v1.RoomR\x05rooms\".\n" +
	"\x12DeleteRoomResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xe9\x02\n" +
	"\vRoomService\x12C\n" +
	"\fFindRoomByID\x12\x1c.chat.v1.FindRoomByIDRequest\x1a\x15.chat.v1.RoomResponse\x12N\n" +
	"\x11FindRoomsByUserID\x12!.chat.v1.FindRoomsByUserIDRequest\x1a\x16.chat.v1.RoomsResponse\x12?\n" +
	"\n" +
	"CreateRoom\x12\x1a.chat.v1.CreateRoomRequest\x1a\x15.chat.v1.RoomResponse\x12=\n" +
	"\tPatchRoom\x12\x19.chat.v1.PatchRoomRequest\x1a\x15.chat.v1.RoomResponse\x12E\n" +
	"\n" +
	"DeleteRoom\x12\x1a.chat.v1.DeleteRoomRequest\x1a\x1b.chat.v1.DeleteRoomResponseB\x18Z\x16internal/chat/proto/v1b\x06proto3"

var (
	file_internal_chat_proto_v1_room_proto_rawDescOnce sync.Once
	file_internal_chat_proto_v1_room_proto_rawDescData []byte
)

func file_internal_chat_proto_v1_room_proto_rawDescGZIP() []byte {
	file_internal_chat_proto_v1_room_proto_rawDescOnce.Do(func() {
		file_internal_chat_proto_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_chat_proto_v1_room_proto_rawDesc), len(file_internal_chat_proto_v1_room_proto_rawDesc)))
	})
	return file_internal_chat_proto_v1_room_proto_rawDescData
}

var file_internal_chat_proto_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_chat_proto_v1_room_proto_goTypes = []any{
	(*Room)(nil),                     // 0: chat.v1.Room
	(*Membership)(nil),               // 1: chat.v1.Membership
	(*FindRoomByIDRequest)(nil),      // 2: chat.v1.FindRoomByIDRequest
	(*FindRoomsByUserIDRequest)(nil), // 3: chat.v1.FindRoomsByUserIDRequest
	(*CreateRoomRequest)(nil),        // 4: chat.v1.CreateRoomRequest
	(*PatchRoomRequest)(nil),         // 5: chat.v1.PatchRoomRequest
	(*DeleteRoomRequest)(nil),        // 6: chat.v1.DeleteRoomRequest
	(*RoomResponse)(nil),             // 7: chat.v1.RoomResponse
	(*RoomsResponse)(nil),            // 8: chat.v1.RoomsResponse
	(*DeleteRoomResponse)(nil),       // 9: chat.v1.DeleteRoomResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_internal_chat_proto_v1_room_proto_depIdxs = []int32{
	10, // 0: chat.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: chat.v1.Room.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chat.v1.Room.memberships:type_name -> chat.v1.Membership
	10, // 3: chat.v1.Membership.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: chat.v1.RoomResponse.room:type_name -> chat.v1.Room
	0,  // 5: chat.v1.RoomsResponse.rooms:type_name -> chat.v1.Room
	2,  // 6: chat.v1.RoomService.FindRoomByID:input_type -> chat.v1.FindRoomByIDRequest
	3,  // 7: chat.v1.RoomService.FindRoomsByUserID:input_type -> chat.v1.FindRoomsByUserIDRequest
	4,  // 8: chat.v1.RoomService.CreateRoom:input_type -> chat.v1.CreateRoomRequest
	5,  // 9: chat.v1.RoomService.PatchRoom:input_type -> chat.v1.PatchRoomRequest
	6,  // 10: chat.v1.RoomService.DeleteRoom:input_type -> chat.v1.DeleteRoomRequest
	7,  // 11: chat.v1.RoomService.FindRoomByID:output_type -> chat.v1.RoomResponse
	8,  // 12: chat.v1.RoomService.FindRoomsByUserID:output_type -> chat.v1.RoomsResponse
	7,  // 13: chat.v1.RoomService.CreateRoom:output_type -> chat.v1.RoomResponse
	7,  // 14: chat.v1.RoomService.PatchRoom:output_type -> chat.v1.RoomResponse
	9,  // 15: chat.v1.RoomService.DeleteRoom:output_type -> chat.v1.DeleteRoomResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_chat_proto_v1_room_proto_init() }
func file_internal_chat_proto_v1_room_proto_init() {
	if File_internal_chat_proto_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_chat_proto_v1_room_proto_rawDesc), len(file_internal_chat_proto_v1_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_chat_proto_v1_room_proto_goTypes,
		DependencyIndexes: file_internal_chat_proto_v1_room_proto_depIdxs,
		MessageInfos:      file_internal_chat_proto_v1_room_proto_msgTypes,
	}.Build()
	File_internal_chat_proto_v1_room_proto = out.File
	file_internal_chat_proto_v1_room_proto_goTypes = nil
	file_internal_chat_proto_v1_room_proto_depIdxs = nil
}
